spring:
  datasource:
    dynamic:
      primary: master
      p6spy: true
      lazy: false
      datasource:
        master:
          username: root
          password: "123456"
          url: jdbc:mysql://127.0.0.1:3306/hokage
          driver-class-name: com.mysql.cj.jdbc.Driver
          init:
            schema: db/schema.sql
          druid:
            initial-size: 5
            max-active: 8
            min-idle: 3
            max-wait: 1000
            validation-query: 'select 1'
        slave_1:
          username: root
          password: "123456"
          url: jdbc:mysql://127.0.0.1:3307/hokage
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 5
            max-active: 8
            min-idle: 3
            max-wait: 1000
            validation-query: 'select 1'
        slave_2:
          username: root
          password: "123456"
          url: jdbc:mysql://127.0.0.1:3307/hokage
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 5
            max-active: 8
            min-idle: 3
            max-wait: 1000
            validation-query: 'select 1'
logging:
  level:
    com.baomidou: debug
server:
  port: 7006